blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .apps import BlogConfig
from .views import ArticleListView, ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, \
    toggle_publish

app_name = BlogConfig.name

urlpatterns = [
    path('articles/', ArticleListView.as_view(), name='articles'),
    path('article/create/', ArticleCreateView.as_view(), name='article_create'),
    path('article/view/<str:slug>/', cache_page(300)(ArticleDetailView.as_view()), name='article_view'),
    path('article/update/<int:pk>/', ArticleUpdateView.as_view(), name='article_update'),
    path('article/delete/<int:pk>', ArticleDeleteView.as_view(), name='article_delete'),
    path('article/toggle_publish/<int:pk>', toggle_publish, name='toggle_publish'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls'), name='mailing'),
    path('blog/', include('blog.urls'), name='blog'),
    path('users/', include('users.urls'), name='users'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import IndexView, AddressListView, AddressCreateView, AddressDetailView, AddressUpdateView, \
    AddressDeleteView, MessageListView, MessageCreateView, MessageDetailView, MessageUpdateView, MessageDeleteView, \
    ScheduleListView, ScheduleCreateView, ScheduleDetailView, ScheduleUpdateView, ScheduleDeleteView, \
    MailingLogListView, MailingLogDetailView, toggle_active, toggle_run_pause

app_name = MailingConfig.name

urlpatterns = [
    path('', cache_page(60)(IndexView.as_view()), name='index'),

    path('addresses/', AddressListView.as_view(), name='addresses'),
    path('addresses/create/', AddressCreateView.as_view(), name='address_create'),
    path('addresses/view/<int:pk>/', AddressDetailView.as_view(), name='address_view'),
    path('addresses/update/<int:pk>', AddressUpdateView.as_view(), name='address_update'),
    path('addresses/delete/<int:pk>', AddressDeleteView.as_view(), name='address_delete'),

    path('messages/', MessageListView.as_view(), name='messages'),
    path('messages/create/', MessageCreateView.as_view(), name='message_create'),
    path('messages/view/<int:pk>/', MessageDetailView.as_view(), name='message_view'),
    path('messages/update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('messages/delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),

    path('schedules/', ScheduleListView.as_view(), name='schedules'),
    path('schedules/create/', ScheduleCreateView.as_view(), name='schedule_create'),
    path('schedules/view/<int:pk>/', ScheduleDetailView.as_view(), name='schedule_view'),
    path('schedules/update/<int:pk>', ScheduleUpdateView.as_view(), name='schedule_update'),
    path('schedules/delete/<int:pk>', ScheduleDeleteView.as_view(), name='schedule_delete'),
    path('schedules/toggle_active/<int:pk>', toggle_active, name='toggle_active'),
    path('schedules/toggle_run_pause/<int:pk>', toggle_run_pause, name='toggle_run_pause'),

    path('mailing_logs/', MailingLogListView.as_view(), name='mailing_logs'),
    path('mailing_logs/view/<int:pk>', MailingLogDetailView.as_view(), name='mailing_log_view'),
]

mailing/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Address(models.Model):
    GENDER = [
        ('m', 'male'),
        ('f', 'female'),
        ('u', 'unknown'),
    ]
    first_name = models.CharField(max_length=50, **NULLABLE, verbose_name='Name')
    last_name = models.CharField(max_length=50, **NULLABLE, verbose_name='Surname')
    email_address = models.EmailField(verbose_name='Email address')
    phone_number = models.CharField(max_length=20, **NULLABLE, verbose_name='Phone number')
    gender = models.CharField(max_length=7, choices=GENDER, default='u', verbose_name='Gender')
    birthday = models.DateField(**NULLABLE, verbose_name='Birthday')
    is_correct = models.BooleanField(default=True, verbose_name='Is correct')
    comment = models.TextField(**NULLABLE, verbose_name='Comment')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Created date')
    modified_date = models.DateTimeField(auto_now=True, verbose_name='Modified date')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                   **NULLABLE, verbose_name='Created by')

    def __str__(self):
        return f'{self.email_address}: {self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'address'
        verbose_name_plural = 'addresses'
        ordering = ('email_address', 'last_name',)


class Message(models.Model):
    description = models.CharField(max_length=150, **NULLABLE, verbose_name='Description')
    subject = models.CharField(max_length=150, **NULLABLE, verbose_name='Subject')
    text_message = models.TextField(**NULLABLE, verbose_name='Message')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Created date')
    modified_date = models.DateTimeField(auto_now=True, verbose_name='Modified date')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                   **NULLABLE, verbose_name='Created by')

    def __str__(self):
        return f'{self.description}/{self.subject}'

    class Meta:
        verbose_name = 'message'
        verbose_name_plural = 'messages'
        ordering = ('created_date',)


class Schedule(models.Model):
    PERIODIC_CHOICES = (
        ('s', 'Single'),
        ('d', 'Daily'),
        ('w', 'Weekly'),
        ('m', 'Monthly'),
    )

    STATUS_CHOICES = (
        ('c', 'Created'),
        ('r', 'Running'),
        ('p', 'Paused'),
        ('f', 'Completed'),
    )

    DAY_OF_WEEK_CHOICES = (
        (1, 'Monday'),
        (2, 'Tuesday'),
        (3, 'Wednesday'),
        (4, 'Thursday'),
        (5, 'Friday'),
        (6, 'Saturday'),
        (7, 'Sunday'),
    )

    description = models.CharField(max_length=200, verbose_name='Description')
    start_date = models.DateField(verbose_name='Start day')
    end_date = models.DateField(verbose_name='End day', **NULLABLE)
    periodic = models.CharField(max_length=1, choices=PERIODIC_CHOICES, verbose_name='Periodic')
    time = models.TimeField(verbose_name='Time to send')
    day_of_week = models.IntegerField(choices=DAY_OF_WEEK_CHOICES,
                                      verbose_name='Day of the week to send', **NULLABLE)
    day_of_month = models.IntegerField(verbose_name='Day of the month to send', **NULLABLE)
    message = models.ForeignKey(Message, on_delete=models.CASCADE, verbose_name='Message')
    addresses = models.ManyToManyField(to=Address, blank=True, verbose_name='Addresses')
    status = models.CharField(default='c', max_length=1, choices=STATUS_CHOICES, verbose_name='Status')
    is_active = models.BooleanField(default=True, verbose_name='Active')
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='Created date')
    modified_date = models.DateTimeField(auto_now=True, verbose_name='Modified date')
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
                                   **NULLABLE, verbose_name='Created by')

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedules'
        ordering = ('-start_date',)
        permissions = [('set_schedule_active_status', 'Can activate/deactivate schedule')]


class MailingLog(models.Model):
    date_of_last_attempt = models.DateTimeField(auto_now=True, verbose_name='Date and time of last attempt')
    status_of_last_attempt = models.BooleanField(default=False, verbose_name='Status of last attempt')
    server_response = models.TextField(verbose_name='Server response', **NULLABLE)
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE, verbose_name='Schedule', **NULLABLE)

    def __str__(self):
        return f'{self.schedule.description}: {self.date_of_last_attempt} - {self.status_of_last_attempt}'

    class Meta:
        verbose_name = 'Mailing log'
        ordering = ('-date_of_last_attempt',)

mailing/views.py
import random

from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from blog.models import Article
from mailing.forms import ScheduleForm, MessageForm, AddressForm
from mailing.models import Address, Message, Schedule, MailingLog
from mailing.services import get_cache
from users.models import User


class GetQuerysetFromCacheMixin:

    def get_queryset(self):
        # Получаем результат запроса из кэша только тех записей, которые создал
        # текущий пользователь (если пользователь - staff, то показываем все записи)
        # Если данных в кэше нет, то запрашиваем в БД, используя фильтр, указанный в kwargs
        if self.request.user.role('managers'):
            kwargs = {}
        else:
            kwargs = {'created_by': self.request.user}
        queryset = get_cache(self.model, kwargs)
        return queryset


class IndexView(generic.View):

    @staticmethod
    def get(request):
        three_random_articles = []
        count_users = User.objects.all().count()
        count_schedules = Schedule.objects.all().count()
        count_active_schedules = Schedule.objects.filter(Q(status='c') | Q(status='r')).count()
        count_unique_addresses = Address.objects.all().distinct('email_address').count()

        # Выбираем три случайные статьи из блога (без повторов)
        all_published_articles = Article.objects.filter(is_published=True)
        num_of_published_articles = all_published_articles.count()
        while len(three_random_articles) < 3:
            i = random.randint(0, num_of_published_articles - 1)
            if all_published_articles[i] not in three_random_articles:
                three_random_articles.append(all_published_articles[i])

        # Формируем контекст для отображения на домашней странице
        context = {
            'count_users': count_users,
            'count_schedules': count_schedules,
            'count_active_schedules': count_active_schedules,
            'count_unique_addresses': count_unique_addresses,
            'object_list': three_random_articles,
        }
        return render(request, 'mailing/index.html', context)


class AddressListView(LoginRequiredMixin, GetQuerysetFromCacheMixin, ListView):
    model = Address


class AddressCreateView(LoginRequiredMixin, CreateView):
    model = Address
    form_class = AddressForm

    def get_success_url(self):
        return reverse('mailing:address_view', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)


class AddressDetailView(LoginRequiredMixin, DetailView):
    model = Address


class AddressUpdateView(LoginRequiredMixin, UpdateView):
    model = Address
    form_class = AddressForm

    def get_success_url(self):
        return reverse('mailing:address_view', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.created_by != self.request.user:
            raise Http404
        return self.object


class AddressDeleteView(LoginRequiredMixin, DeleteView):
    model = Address
    success_url = reverse_lazy('mailing:addresses')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.created_by != self.request.user:
            raise Http404
        return self.object


class MessageListView(LoginRequiredMixin, GetQuerysetFromCacheMixin, ListView):
    model = Message


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse('mailing:message_view', args=[self.object.pk])

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.save()
        return super().form_valid(form)


class MessageDetailView(LoginRequiredMixin, DetailView):
    model = Message


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm

    def get_success_url(self):
        return reverse('mailing:message_view', args=[self.kwargs.get('pk')])

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.created_by != self.request.user:
            raise Http404
        return self.object


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('mailing:messages')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.created_by != self.request:
            raise Http404
        return self.object


class ScheduleListView(LoginRequiredMixin, GetQuerysetFromCacheMixin, ListView):
    model = Schedule


class ScheduleCreateView(LoginRequiredMixin, CreateView):
    model = Schedule
    form_class = ScheduleForm

    def get_success_url(self):
        return reverse('mailing:schedule_view', args=[self.object.pk])
        # return reverse('mailing:schedules')

    def form_valid(self, form):
        self.object = form.save()
        self.object.created_by = self.request.user
        self.object.is_active = True  # Присваиваю True вручную, так как вопреки описанию в модели Schedule
        #  значения данного поля по умолчанию default=True - при создании Schedule присваивается False
        self.object.save()
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user  # Передаем пользователя в форму
        return kwargs


class ScheduleDetailView(LoginRequiredMixin, DetailView):
    model = Schedule

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        schedule_item = Schedule.objects.get(pk=self.kwargs.get('pk'))
        address_item = Address.objects.filter(schedule=self.kwargs.get('pk'))
        context_data['schedule_pk'] = schedule_item.pk
        context_data['address_item'] = address_item

        return context_data


class ScheduleUpdateView(LoginRequiredMixin, UpdateView):
    model = Schedule
    form_class = ScheduleForm

    def get_success_url(self):
        return reverse('mailing:schedule_view', args=[self.kwargs.get('pk')])

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.user.role('managers'):
            kwargs['user'] = None
        else:
            kwargs['user'] = self.request.user  # Передаем пользователя в форму
        return kwargs

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.created_by != self.request.user or self.request.user.role('managers'):
            raise Http404
        return self.object


class ScheduleDeleteView(LoginRequiredMixin, DeleteView):
    model = Schedule
    success_url = reverse_lazy('mailing:schedules')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.created_by != self.request.user or self.request.user.role('managers'):
            raise Http404
        return self.object


@permission_required('mailing.set_schedule_active_status')
def toggle_active(request, pk):
    schedule = Schedule.objects.get(pk=pk)
    # Переключаем статус is_active, если только рассылка не завершена
    if schedule.status != 'f':
        schedule.is_active = {schedule.is_active: False,
                              not schedule.is_active: True}[True]
        schedule.save()
    else:
        messages.error(request, 'You cannot deactivate completed schedule')
    return redirect(reverse('mailing:schedules'))


@login_required
def toggle_run_pause(request, pk):
    schedule = Schedule.objects.get(pk=pk)
    # Переключаем статус running/pause, если только рассылка не завершена
    if schedule.status != 'f':
        schedule.status = {schedule.status == 'p': 'c',
                           schedule.status == 'c' or schedule.status == 'r': 'p'}[True]
        schedule.save()
    else:
        messages.error(request, 'You cannot run/pause completed schedule')
    return redirect(reverse('mailing:schedules'))


class MailingLogListView(LoginRequiredMixin, ListView):
    model = MailingLog

    def get_queryset(self):
        # Получаем логи из кэша только те, рассылки, которые создал
        # текущий пользователь (если пользователь - staff, то показываем все логи)
        # Если данных в кэше нет, то запрашиваем в БД, используя фильтр, указанный в kwargs
        if self.request.user.role('managers'):
            kwargs = {}
        else:
            kwargs = {'schedule__created_by': self.request.user}
        queryset = get_cache(self.model, kwargs)
        return queryset


class MailingLogDetailView(LoginRequiredMixin, DetailView):
    model = MailingLog

mailing/templates/mailing/mailinglog_detail.html
{% extends 'mailing/base.html' %}

{% block content %}
<!--<div class="card" style="max-height: 600px;">-->
<div class="card">
    <div class="row g-0">
        <div class="card-header">
            <p><h4 class="card-title"><strong>Mailing Log Detail</strong></h4></p>
        </div>
        <div class="col">
            <div class="card-body">
                <div class="container-fluid">
                    <dl class="row">
                        <dt class="col-sm-2">Date of last attempt</dt>
                        <dd class="col-sm-10">{{ object.date_of_last_attempt|date:"d M Y H:i:s" }}</dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-2">Status of attempt</dt>
                        <dd class="col-sm-10">
                          {% if object.status_of_last_attempt %}
                            Success
                          {% else %}
                            Fail
                          {% endif %}
                        </dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-2">Server response</dt>
                        <dd class="col-sm-10">{{ object.server_response }}</dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-2">Message periodicity</dt>
                        <dd class="col-sm-10">{{ object.schedule.get_periodic_display }}</dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-2">Message subject</dt>
                        <dd class="col-sm-10">{{ object.schedule.message.subject }}</dd>
                    </dl>
                    <dl class="row">
                        <dt class="col-sm-2">Message text</dt>
                        <dd class="col-sm-10">{{ object.schedule.message.text_message|linebreaksbr }}</dd>
                    </dl>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-outline-secondary btn-sm" href="{% url 'mailing:mailing_logs' %}">All Mailing Logs</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/schedule_detail.html
{% extends 'mailing/base.html' %}
{% load users_tags %}
{% block content %}
    <div class="card">
        <div class="card-header">
            <div class="card-title"><strong><p><h4>Schedule - {{ object.description }}</p></h4></strong></div>
        </div>

        <div class="card-body">
                <dl class="row">
                    <dt class="col-sm-3">Status</dt>
                    <dd class="col-sm-9">{{ object.get_status_display }}</dd>

                    <dt class="col-sm-3">Start date - End date</dt>
                    <dd class="col-sm-9">{{ object.start_date }} - {{ object.end_date }}</dd>

                    <dt class="col-sm-3">Periodic</dt>
                    <dd class="col-sm-9">
                        {% if object.periodic == "s" %}
                            Once on {{ object.start_date|date:"d M Y" }} at {{ object.time|time:"H:i" }}
                        {% elif object.periodic == "d" %}
                            Daily at {{ object.time|time:"H:i" }}
                        {% elif object.periodic == "w" %}
                            Weekly every {{ object.get_day_of_week_display }}
                        {% elif object.periodic == "m" %}
                            Monthly every {{ object.day_of_month }} day
                        {% endif %}
                    </dd>

                    <dt class="col-sm-3">Message subject</dt>
                    <dd class="col-sm-9">{{ object.message.subject }}</dd>

                    <dt class="col-sm-3">Message</dt>
                    <dd class="col-sm-9">{{ object.message.text_message|linebreaksbr }}</dd>

                    {# <dt class="col-sm-3">Gender</dt> #}
                    {# <dd class="col-sm-9">{{ object.get_gender_display|title }}</dd> #}
                    {# <dd class="col-sm-9">{{ object.gender|title }}</dd> #}
                </dl>
        </div>

        <div class="card-footer">
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a class="btn btn-outline-secondary btn-sm" href="{% url 'mailing:schedules' %}">All
                        schedules</a>
                    {% if request.user|has_group:"managers" %}
                    <a class="btn btn-outline-secondary btn-sm"
                       href="{% url 'mailing:toggle_run_pause' object.pk %}">
                        {% if object.is_active and object.status != "f" %}
                            {% if object.status == "p" %}
                                Run
                            {% else %}
                                Pause
                            {% endif %}
                        {% endif %}
                    </a>
                    {% else %}
                    <a class="btn btn-outline-secondary btn-sm"
                       href="{% url 'mailing:schedule_update' object.pk %}">Edit</a>
                    <a class="btn btn-outline-danger btn-sm"
                       href="{% url 'mailing:schedule_delete' object.pk %}">Delete</a>
                    {% endif %}
                </div>
                <small>Created at: <strong>{{ object.created_date|date:"d M Y H:i:s" }}</strong>, Modified at:
                    <strong>{{ object.modified_date|date:"d M Y H:i:s" }}</strong></small>
            </div>
        </div>
    </div>

<br>

<div class="card">
    <div class="card-header">
        <strong class="text-body-secondary">Addresses</strong>
    </div>
    <div class="card-body">
            <dl class="row">
                {% for address in address_item %}

                    <dt class="col-sm-3">{{ address.email_address }}</dt>
                    <dd class="col-sm-9">{{ address.first_name }} {{ address.last_name }}</dd>

                {% endfor %}
            </dl>
            {% if user.is_authenticated %}
            <div class="btn-group py-3">
                {# <a class="btn btn-sm btn-outline-secondary" href="{% url 'catalog:version_list' object.pk %}">Manage versions</a> #}
            </div>
            {% endif %}
    </div>
</div>

{% endblock %}

mailing/templates/mailing/schedule_list.html
{% extends 'mailing/base.html' %}
{% load users_tags %}
{% block content %}

<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h3>Schedules</h3>
    {% if not request.user|has_group:"managers" %}
    <div class="btn-toolbar mb-2 mb-md-0">
        <a type="button" class="btn btn-sm btn-secondary" href="{% url 'mailing:schedule_create' %}">Add
            new</a>
    </div>
    {% endif %}
</div>

<div class="table-responsive small">
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th>Description</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Periodic</th>
            <th>Message subject</th>
            <th>Status</th>
            <th>Actions</th>
        </tr>
        </thead>

        {% for object in object_list %}
        <tr>
            <td>{{ object.description|truncatechars:30 }}</td>
            <td>{{ object.start_date|date:"d M Y" }}</td>
            <td>{{ object.end_date|date:"d M Y" }}</td>

            {% if object.periodic == "s" %}
                <td>Once on {{ object.start_date|date:"d M Y" }} at {{ object.time|time:"H:i" }}</td>
            {% elif object.periodic == "d" %}
                <td>Daily at {{ object.time|time:"H:i" }}</td>
            {% elif object.periodic == "w" %}
                <td>Weekly every {{ object.get_day_of_week_display }} at {{ object.time|time:"H:i" }}</td>
            {% elif object.periodic == "m" %}
                <td>Monthly every {{ object.day_of_month }} day at {{ object.time|time:"H:i" }}</td>
            {% endif %}

            <td>{{ object.message.subject|truncatechars:30 }}</td>
            <td>
                {% if object.is_active %}
                    {% if object.status == "c" %}
                        <span class="badge rounded-pill text-bg-primary opacity-75">
                    {% elif object.status == "r" %}
                        <span class="badge rounded-pill text-bg-success opacity-75">
                    {% elif object.status == "p" %}
                        <span class="badge rounded-pill text-bg-warning opacity-75">
                    {% elif object.status == "f" %}
                        <span class="badge rounded-pill text-bg-secondary opacity-75">
                    {% endif %}
                    {{ object.get_status_display }}</span>
                {% else %}
                    <span class="badge rounded-pill text-bg-danger opacity-75">Not active</span>
                {% endif %}
            </td>

            <td>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    {% if request.user|has_group:"managers" %}
                        <a type="button" class="btn" href="{% url 'mailing:toggle_active' object.pk %}"
                           style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                            {% if object.status != "f" %}
                                {% if object.is_active %}
                                    Deactivate
                                {% else %}
                                    Activate
                                {% endif %}
                            {% endif %}
                        </a>
                        <a type="button" class="btn" href="{% url 'mailing:schedule_view' object.pk %}"
                           style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                            View
                        </a>
                    {% else %}
                        <a type="button" class="btn" href="{% url 'mailing:toggle_run_pause' object.pk %}"
                               style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                                {% if object.is_active and object.status != "f" %}
                                    {% if object.status == "p" %}
                                        Run
                                    {% else %}
                                        Pause
                                    {% endif %}
                                {% endif %}
                            </a>
                        <a type="button" class="btn" href="{% url 'mailing:schedule_view' object.pk %}"
                           style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                            View
                        </a>
                        <a type="button" class="btn" href="{% url 'mailing:schedule_update' object.pk %}"
                           style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                            Edit
                        </a>
                        <a type="button" class="btn" href="{% url 'mailing:schedule_delete' object.pk %}"
                           style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .25rem; --bs-btn-font-size: .75rem;">
                            Delete
                        </a>
                    {% endif %}
                </div>
            </td>
        </tr>
        {% endfor %}
    </table>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li class="{{ message.tags }}">
            {{ message|safe }}
            <a type="button" class="btn" href="{% url 'users:users' %}"
               style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .8rem;">✕</a>
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

<!--#TODO: Может реализовать DetailView в нижней половине окна?-->
<!--<div class="my-3 p-3 bg-body rounded shadow-sm fixed-bottom">-->
<!--        <div class="container px-8 py-0">-->
<!--&lt;!&ndash;    <div class="container py-4">&ndash;&gt;-->

<!--        <div class="h-20 p-0 bg-body-tertiary border rounded-3">-->
<!--            <div class="container-fluid py-3">-->

<!--                <h5 class="display-6">123</h5>-->
<!--                <p class="col-md-10 fs-4">456</p>-->
<!--                <button class="btn btn-primary btn-lg" type="button">Buy</button>-->
<!--            </div>-->

<!--        </div>-->

<!--    </div>-->
<!--</div>-->
{% endblock %}